var VERSION='0.1'
var FULL_VERSION='0.1'
var AUTHORS='Microsoft'

use-standard-lifecycle
k-standard-goals
custom-goals

#initialize
  dotnet command='msbuild tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode/run.proj /t:GenerateCode'